defmodule GovernanceCore.Protocols.Fuzzer do
  @moduledoc """
  GenServer that fuzzes the UMP parser with random binary data generated by stream_data.
  """
  use GenServer
  require Logger
  alias GovernanceCore.Protocols.UMP.Parser

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, opts, name: __MODULE__)
  end

  @impl true
  def init(_opts) do
    # Start fuzzing periodically
    schedule_fuzz()
    {:ok, %{}}
  end

  @impl true
  def handle_info(:fuzz, state) do
    do_fuzz()
    schedule_fuzz()
    {:noreply, state}
  end

  defp schedule_fuzz do
    # Fuzz every 5 seconds
    Process.send_after(self(), :fuzz, 5000)
  end

  defp do_fuzz do
    generator = StreamData.binary()
    # Take 100 random binaries per fuzz cycle
    binaries = Enum.take(generator, 100)

    Enum.each(binaries, fn bin ->
      try do
        Parser.parse_frame(bin)
      rescue
        e ->
          Logger.warning("Fuzzer encountered rescue: #{inspect(e)} with input: #{inspect(bin)}")
      catch
        kind, value ->
          Logger.warning("Fuzzer encountered catch: #{inspect(kind)}, #{inspect(value)} with input: #{inspect(bin)}")
      end
    end)
  end
end
