defmodule GovernanceCore.Protocols.Fuzzer do
  @moduledoc """
  A background worker that continuously fuzzes the UMP parser using random binary payloads
  generated by StreamData, to uncover potential unhandled exceptions or pattern matching errors.
  """
  use GenServer
  require Logger

  @interval 1000 # Run fuzzing every 1 second

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, opts, name: __MODULE__)
  end

  def init(state) do
    schedule_fuzz()
    {:ok, state}
  end

  def handle_info(:fuzz, state) do
    fuzz_ump_parser()
    schedule_fuzz()
    {:noreply, state}
  end

  defp schedule_fuzz do
    Process.send_after(self(), :fuzz, @interval)
  end

  defp fuzz_ump_parser do
    # Generate 100 random binary strings to test the parser
    payloads = StreamData.binary() |> Enum.take(100)

    Enum.each(payloads, fn payload ->
      try do
        _ = GovernanceCore.Protocols.UMP.Parser.parse_frame(payload)
      rescue
        e in [MatchError, FunctionClauseError, RuntimeError, ArgumentError] ->
          Logger.error("UMP Parser crashed on payload: #{inspect(payload)} - Error: #{inspect(e)}")
      end
    end)
  end
end
