defmodule GovernanceCore.Protocols.Fuzzer do
  @moduledoc """
  A GenServer that continually fuzzes the UMP Parser using random binary data
  generated by StreamData to ensure robust pattern matching and error handling.
  """
  use GenServer
  require Logger

  # 1 minute fuzzing interval
  @interval 60 * 1000

  def start_link(opts) do
    GenServer.start_link(__MODULE__, opts, name: __MODULE__)
  end

  @impl true
  def init(_opts) do
    schedule_fuzz()
    {:ok, %{}}
  end

  @impl true
  def handle_info(:fuzz, state) do
    perform_fuzz()
    schedule_fuzz()
    {:noreply, state}
  end

  defp schedule_fuzz do
    Process.send_after(self(), :fuzz, @interval)
  end

  def perform_fuzz do
    Logger.debug("Starting UMP Fuzzing...")

    StreamData.binary()
    |> Enum.take(100)
    |> Enum.each(fn payload ->
      try do
        GovernanceCore.Protocols.UMP.Parser.parse(payload)
      rescue
        e in [MatchError, FunctionClauseError, RuntimeError, ArgumentError] ->
          Logger.error("UMP Parser Fuzzing Error: #{Exception.message(e)}")
      end
    end)
  end
end
