defmodule GovernanceCore.Monitoring.SkillTracker do
  @moduledoc """
  A GenServer that dynamically manages SKILL.md documentation by discovering
  modules in the `governance_core` application, chunking them to enforce a
  1024-character limit per file, and writing generated YAML to the project's
  source `priv` directory.
  """
  use GenServer
  require Logger

  # Continuous interval: 5 minutes
  @interval 5 * 60 * 1000

  def start_link(_opts) do
    GenServer.start_link(__MODULE__, %{}, name: __MODULE__)
  end

  @impl true
  def init(state) do
    schedule_update()
    {:ok, state}
  end

  @impl true
  def handle_info(:update_skills, state) do
    update_skill_docs()
    schedule_update()
    {:noreply, state}
  end

  defp schedule_update do
    Process.send_after(self(), :update_skills, @interval)
  end

  def update_skill_docs do
    Logger.info("Starting SKILL.md documentation update...")

    # Discover modules
    case :application.get_key(:governance_core, :modules) do
      {:ok, modules} ->
        chunked_docs = chunk_modules_for_yaml(modules)
        write_skill_files(chunked_docs)
        Logger.info("SKILL.md update completed. Generated #{length(chunked_docs)} files.")

      :undefined ->
        Logger.error("Failed to retrieve modules for :governance_core application.")
    end
  end

  # Dynamically chunks modules ensuring each generated YAML is under 1024 chars
  defp chunk_modules_for_yaml(modules) do
    Enum.reduce(modules, [{[], 0}], fn mod, acc ->
      [{current_chunk, current_len} | rest] = acc

      mod_str = to_string(mod)

      # Using multiline string interpolation with explicit indentation for YAML block scalars
      mod_yaml = """
      - module: #{mod_str}
        description: |
          Documentation for #{mod_str}.
          Autogenerated by SkillTracker.
      """

      mod_yaml_len = String.length(mod_yaml)

      if current_len + mod_yaml_len > 1024 and current_chunk != [] do
        # Start a new chunk
        [{[mod_yaml], mod_yaml_len}, {current_chunk, current_len} | rest]
      else
        # Add to current chunk
        [{[mod_yaml | current_chunk], current_len + mod_yaml_len} | rest]
      end
    end)
    |> Enum.reverse()
    |> Enum.map(fn {chunk, _len} ->
      # Reverse the chunk back to original order and join
      chunk_content = chunk |> Enum.reverse() |> Enum.join("")
      "skills:\n" <> chunk_content
    end)
  end

  defp write_skill_files(chunked_docs) do
    # Memory constraint says: if files must be version-controlled (e.g. SKILL.md),
    # write them directly to the source directory using Path.join(File.cwd!(), "priv")
    priv_dir = Path.join(File.cwd!(), "priv")

    # Ensure priv directory exists
    File.mkdir_p!(priv_dir)

    Enum.with_index(chunked_docs, 1)
    |> Enum.each(fn {content, index} ->
      filename = if index == 1, do: "SKILL.md", else: "SKILL_#{index}.md"
      filepath = Path.join(priv_dir, filename)

      # Handle write with a case statement to prevent GenServer crashes from I/O
      case File.write(filepath, content) do
        :ok -> :ok
        {:error, reason} ->
          Logger.error("Failed to write #{filepath}: #{inspect(reason)}")
      end
    end)
  end
end
