defmodule GovernanceCore.Monitoring.SkillTracker do
  @moduledoc """
  GenServer that monitors tools and functions to automatically update SKILL.md.
  It tracks loaded functions dynamically using Code.all_loaded() and filters
  for those under Elixir.GovernanceCore, enforcing universal standards.
  """
  use GenServer
  require Logger

  # 1 hour in milliseconds
  @interval 60 * 60 * 1000
  @max_chars 1024

  def start_link(_opts) do
    GenServer.start_link(__MODULE__, %{}, name: __MODULE__)
  end

  def init(state) do
    schedule_update()
    {:ok, state}
  end

  def handle_info(:update_skills, state) do
    update_skill_md()
    schedule_update()
    {:noreply, state}
  end

  defp schedule_update do
    Process.send_after(self(), :update_skills, @interval)
  end

  def update_skill_md do
    Logger.info("Starting SKILL.md standardization update...")

    modules =
      Code.all_loaded()
      |> Enum.map(fn {mod, _file} -> mod end)
      |> Enum.filter(fn mod ->
        String.starts_with?(Atom.to_string(mod), "Elixir.GovernanceCore")
      end)

    docs_data =
      Enum.reduce(modules, [], fn mod, acc ->
        case Code.fetch_docs(mod) do
          {:docs_v1, _anno, _lang, _format, _module_doc, _metadata, docs} ->
            module_info = extract_functions(mod, docs)
            acc ++ module_info

          _ ->
            acc
        end
      end)

    content = format_skill_md(docs_data)

    case File.write("SKILL.md", content) do
      :ok -> Logger.info("SKILL.md successfully updated.")
      {:error, reason} -> Logger.error("Failed to update SKILL.md: #{inspect(reason)}")
    end
  end

  defp extract_functions(mod, docs) do
    Enum.reduce(docs, [], fn
      {{:function, name, arity}, _anno, _signatures, doc, _meta}, acc ->
        doc_str =
          case doc do
            %{"en" => en_doc} -> en_doc
            _ -> "No documentation available."
          end

        # Enforce 1024 character limit
        doc_str =
          if String.length(doc_str) > @max_chars do
            String.slice(doc_str, 0, @max_chars - 3) <> "..."
          else
            doc_str
          end

        [%{module: inspect(mod), function: name, arity: arity, doc: doc_str} | acc]

      _, acc ->
        acc
    end)
  end

  defp format_skill_md(docs_data) do
    header = """
    ---
    description: "Automated Skills Documentation"
    last_updated: "#{DateTime.utc_now() |> DateTime.to_iso8601()}"
    ---

    # Skills

    This file is automatically generated and updated by GovernanceCore.Monitoring.SkillTracker.

    """

    Enum.reduce(docs_data, header, fn item, acc ->
      acc <>
        """
        ## #{item.module}.#{item.function}/#{item.arity}
        #{item.doc}

        """
    end)
  end
end
