defmodule GovernanceCore.Monitoring.SkillTracker do
  @moduledoc """
  Periodically scans application modules and updates the SKILL.md file
  to ensure all tools and skills are documented according to standards.
  """
  use GenServer
  require Logger

  @skill_file "SKILL.md"
  @interval 60 * 60 * 1000 # 1 hour

  def start_link(_opts) do
    GenServer.start_link(__MODULE__, %{}, name: __MODULE__)
  end

  def init(state) do
    schedule_update()
    {:ok, state}
  end

  def handle_info(:update, state) do
    update_skills()
    schedule_update()
    {:noreply, state}
  end

  defp schedule_update do
    Process.send_after(self(), :update, @interval)
  end

  def update_skills do
    Logger.info("Running SkillTracker to update #{@skill_file}...")

    case :application.get_key(:governance_core, :modules) do
      {:ok, modules} ->
        skill_content =
          modules
          |> Enum.filter(&is_tool_module?/1)
          |> Enum.map(&extract_skill_yaml/1)
          |> Enum.join("\n\n")

        header = """
        # Agent Skills & Tools

        This file is auto-generated by GovernanceCore.Monitoring.SkillTracker.
        Do not edit manually.

        """

        File.write!(@skill_file, header <> skill_content)
        Logger.info("SkillTracker updated #{@skill_file} successfully.")

      :undefined ->
        Logger.error("SkillTracker could not load modules from :governance_core application")
    end
  end

  defp is_tool_module?(mod) do
    # For now, we'll document protocols and core task logic as tools/skills
    mod_str = to_string(mod)
    String.starts_with?(mod_str, "Elixir.GovernanceCore.Protocols.") or
      String.starts_with?(mod_str, "Elixir.GovernanceCore.TaskEngine")
  end

  defp extract_skill_yaml(mod) do
    mod_name = inspect(mod)

    docs =
      case Code.fetch_docs(mod) do
        {:docs_v1, _, :elixir, "text/markdown", %{"en" => en_doc}, _, _} -> en_doc
        _ -> "No documentation provided."
      end

    # Enforce 1024 char limit on the description BEFORE interpolating
    truncated_docs = String.slice(docs, 0, 1024)

    # Indent multiline strings properly for YAML block scalar (key: |)
    indented_docs =
      truncated_docs
      |> String.split("\n")
      |> Enum.map(fn line -> "  " <> line end)
      |> Enum.join("\n")

    """
    ---
    skill: #{mod_name}
    description: |
    #{indented_docs}
    ---
    """
  end
end
