defmodule GovernanceCore.AXAudit do
  @moduledoc """
  Runs a nightly audit of the application to ensure it remains "Agent-Friendly".
  Checks for:
  - Semantic HTML structure (presence of <main>, <h1>, <article>)
  - Accessibility of SKILL.md files
  - Low complexity (avoiding heavy JS blocking)
  """
  use GenServer
  require Logger

  # 5 minutes in milliseconds
  @interval 5 * 60 * 1000

  def start_link(_opts) do
    GenServer.start_link(__MODULE__, %{}, name: __MODULE__)
  end

  def init(state) do
    schedule_audit()
    {:ok, state}
  end

  def handle_info(:audit, state) do
    perform_audit()
    schedule_audit()
    {:noreply, state}
  end

  defp schedule_audit do
    Process.send_after(self(), :audit, @interval)
  end

  def perform_audit do
    Logger.info("Starting Continuous AX Audit...")

    base_url = GovernanceCoreWeb.Endpoint.url()
    endpoints = ["/", "/agents", "/dashboard/traffic", "/api/mcp"]

    results = Enum.map(endpoints, fn path ->
      url = base_url <> path
      check_endpoint(url)
    end)

    failures = Enum.filter(results, fn {status, _} -> status == :error end)

    if Enum.empty?(failures) do
      Logger.info("AX Audit Passed: All endpoints are Agent-Friendly.")
    else
      Logger.error("AX Audit Failed: #{inspect(failures)}")
    end
  end

  defp check_endpoint(url) do
    if String.ends_with?(url, "/api/mcp") do
      check_mcp_endpoint(url)
    else
      case Req.get(url) do
        {:ok, %{status: 200, body: body}} ->
          if is_agent_friendly?(body) do
            {:ok, url}
          else
            {:error, "Endpoint #{url} is not agent-friendly (missing semantic tags or too complex)"}
          end
        {:ok, %{status: status}} ->
          {:error, "Endpoint #{url} returned status #{status}"}
        {:error, reason} ->
          {:error, "Failed to fetch #{url}: #{inspect(reason)}"}
      end
    end
  end

  defp check_mcp_endpoint(url) do
    {time, result} =
      :timer.tc(fn ->
        Req.get(url, decode_body: false)
      end)

    # Convert microseconds to milliseconds
    time_ms = time / 1000

    cond do
      time_ms > 1000 ->
        reason = {:error, :timeout}
        trigger_fix(reason)
        {:error, "Endpoint #{url} response time exceeded 1000ms (#{time_ms}ms)"}

      true ->
        case result do
          {:ok, %{status: 200, body: body}} ->
            case Jason.decode(body) do
              {:ok, _json} ->
                {:ok, url}
              {:error, _error} ->
                reason = {:error, :invalid_json}
                trigger_fix(reason)
                {:error, "Endpoint #{url} returned invalid JSON schema"}
            end

          {:ok, %{status: status}} ->
            {:error, "Endpoint #{url} returned status #{status}"}

          {:error, reason} ->
            {:error, "Failed to fetch #{url}: #{inspect(reason)}"}
        end
    end
  end

  defp is_agent_friendly?(html) do
    # Simple heuristic checks for semantic structure
    has_main = String.contains?(html, "<main")
    has_h1 = String.contains?(html, "<h1")
    # Check for excessive script usage might be tricky with simple string matching,
    # but we can check if the ratio of script tags to content is high or just ensure main content exists.

    has_main && has_h1
  end

  defp trigger_fix(reason) do
    Logger.info("Triggering automated fix for AX Audit failure: #{inspect(reason)}")

    title = "🤖 [AX Audit] Automated Fix"
    search_query = "is:pr is:open \"#{title}\""

    try do
      case System.cmd("gh", ["pr", "list", "--search", search_query]) do
        {output, 0} ->
          if String.trim(output) == "" do
            create_automated_pr(title, reason)
          else
            Logger.info("Existing PR found for AX Audit failure. Skipping PR creation.")
          end

        {_, exit_code} ->
          Logger.error("Failed to check for existing PRs. gh exit code: #{exit_code}")
      end
    rescue
      e in ErlangError ->
        Logger.error("Failed to execute gh CLI: #{inspect(e)}")
    end
  end

  defp create_automated_pr(title, reason) do
    Logger.info("Creating automated PR for AX Audit failure...")

    fix_file_path = Path.join(File.cwd!(), "priv/ax_audit_fix.log")
    fix_content = "Automated fix applied for AX Audit failure. Reason: #{inspect(reason)}\n"

    case File.write(fix_file_path, fix_content, [:append]) do
      :ok ->
        branch_name = "ax-audit-fix-#{System.system_time(:second)}"

        try do
          System.cmd("git", ["checkout", "-b", branch_name])
          System.cmd("git", ["add", fix_file_path])
          System.cmd("git", ["commit", "-m", title])

          case System.cmd("gh", ["pr", "create", "--title", title, "--body", "Automated fix generated by AX Audit.", "--head", branch_name]) do
            {_, 0} ->
              Logger.info("Automated PR created successfully.")
            {output, exit_code} ->
              Logger.error("Failed to create PR. Exit code: #{exit_code}, Output: #{output}")
          end

          # Return to previous branch (assumes 'main' or similar)
          System.cmd("git", ["checkout", "-"])
        rescue
          e in ErlangError ->
            Logger.error("Failed to execute git or gh CLI during PR creation: #{inspect(e)}")
        end

      {:error, write_reason} ->
        Logger.error("Failed to write fix file: #{inspect(write_reason)}")
    end
  end
end
